### PR TITLE
NPE-517: Remove NewRelic transaction clearing as it's no longer needed / compatible with newer versions of newrelic_rpm

### PR DESCRIPTION
**Pull request by obrie**
We're only running into this now because it's not triggered with the preforked worker strategy.  Need to test.

### CODE REVIEW

**Review by ehealy — APPROVED** [review]
LGTM for testing.

**Review by alanbrent — APPROVED** [review]
LGTM

**Comment by alanbrent** [comment]
Oh, please increment the version accordingly

**Comment by StabbyCutyou** [comment]
Hey, have we considered adding support for data dog?

**Pull request merged**
